// ===========================================================================
// SINGLE SOURCE OF TRUTH for the site's color palette.
//
// Change a value here, run `npm run build`, and it propagates everywhere:
//   • docs/theme.css            — the :root CSS custom properties (GENERATED)
//   • docs/styles.css           — reads them all via var(--…) and color-mix()
//   • the /r/<slug>/ share pages — scripts/lib/stub.mjs imports PALETTE
//
// Do NOT hand-edit docs/theme.css (it is overwritten on every build), and do
// NOT reintroduce raw hex values in styles.css or stub.mjs — add/derive from a
// token here instead so the palette stays editable in one place.
// ===========================================================================

// Each key becomes a CSS custom property `--<kebab-key>` in :root, in this order.
export const PALETTE = {
  cream: '#ece3cd',        // warm parchment (page background)
  card: '#f8f2e1',         // creamier card stock
  ink: '#211a14',          // warm near-black (primary text)
  accent: '#9c3620',       // deep brick — the primary accent
  'accent-deep': '#7c2917', // darker brick for hovers / pressed states
  gold: '#9a7223',         // brass — signature secondary; decorative / large text only
  olive: '#4f6b2c',        // veg / green tags, "great fit" verdicts
  stone: '#877a63',        // muted text
  rule: '#d3c6aa',         // thin rules
};

const kebab = (k) => k.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());

// Render PALETTE as a `:root { … }` block for docs/theme.css.
export function themeCss() {
  const lines = Object.entries(PALETTE).map(([k, v]) => `  --${kebab(k)}: ${v};`);
  return [
    '/* GENERATED by scripts/build.mjs from scripts/lib/theme.mjs — do not hand-edit. */',
    '/* Edit the palette in scripts/lib/theme.mjs, then run `npm run build`. */',
    ':root {',
    ...lines,
    '}',
    '',
  ].join('\n');
}
